metrics.py refactor
AI-SDC/AI-SDC pull request #111
Opened 2023-04-19 07:37 UTC by yolaj-nhs

Changes made:

- Moved metrics.py up a level (from 'attacks' to main aisdc folder)
- Separated the 'get probabilities' and 'get metrics' functionality, to avoid users needing to pass in training data and a model to calculate the metrics. This means the get_metrics function can be used to calculate the metrics for any model which we have prediction labels and true labels
- Added a separate 'get_probabilities' function which takes in a model and dataset and calculates the predicted probabilities (this was originally done inside get_metrics)
- Taken the min_max_disc function out of mia_extremecase.py and removed this file, since that function was the only thing inside the file. Happy to revert this change if people disagree with this!
- Updated all function calls throughout aisdc to match the new metrics.py function syntax

2023-04-24 09:09 UTC, jim-smith commented
@yolaj-nhs this is failing the Ci tests.
Having quick look at th code, ther are a few bits that probably coding purists might not like e.g.
if permute_rows == True and len(y_test) == 0:

could just be:
if permute_rows  and len(y_test) == 0:

2023-04-24 09:23 UTC, yolaj-nhs commented
Quick note: I'm aware tests are failing, I'm in the process of fixing these

2023-04-24 11:27 UTC, jim-smith commented
If you can't force the exceptions to kick in in your tests, please exempt those lines from the code coverage tests so we know we have maintained 100% coverage of the main code.

- it took me tens of hours after GRAIMatter had finished writing tests to reach that target.

2023-04-25 08:05 UTC, simonrnss approved these changes
All looks great to me -- happy for this to be merged in

2023-04-25 08:07 UTC, simonrnss commented
> All major changes are included as the top comment in this PR. Something important which might need reverted, I've taken the min_max_disc function out of mia_extremecase.py and removed this file, since that function was the only thing inside the file. Happy to revert this change if people disagree with this!

I think this makes sense -- fits better into metrics.py

2023-04-26 10:11 UTC, rpreen requested changes
just a few minor things to clean up...

2023-04-26 10:11 UTC, rpreen commented on aisdc/metrics.py
> +    if permute_rows is True and y_test is None:
`is True`  :cry:

2023-04-26 10:11 UTC, rpreen commented on aisdc/metrics.py
> +    if permute_rows is True:
`is True` :cry:

2023-04-26 10:11 UTC, rpreen submitted a review, later dismissed
just a few minor things to clean up...

2023-04-26 10:27 UTC, rpreen commented on aisdc/metrics.py
> +    clf, X_test: np.ndarray, y_test: np.ndarray = None, permute_rows: bool = None
Shouldn't `permute_rows` be default set to `False` and not `None` ? None is not a bool?

2023-04-26 10:29 UTC, rpreen commented on aisdc/metrics.py
> +    clf, X_test: np.ndarray, y_test: np.ndarray = None, permute_rows: bool = None
also `y_test: np.ndarray = None` -- None is not an ndarray

2023-04-27 13:28 UTC, merged