Move files for release (issue #193)
AI-SDC/AI-SDC pull request #197
Opened 2023-07-07 13:01 UTC by yolaj-nhs

Add a function into attack_report_formatter.py which will move all of the files generated by the release process into two folders:

- training_artefacts (or similar name) - files generated in testing process (not released)
- release_files - files to be released, which will contain four files:
   - the JSON of the attack output
   - the JSON of the target
   - the model to be released
   - the final .txt recommendation

2023-07-07 13:58 UTC, closed without merging

2023-07-10 09:24 UTC, simonrnss commented on aisdc/attacks/attack_report_formatter.py
> +            dest = artefacts_dir + "/" + os.path.basename(filename).split("/")[-1]
safer to use `os.sep` instead of the explicit use of "/"?

2023-07-10 09:24 UTC, simonrnss commented on aisdc/attacks/attack_report_formatter.py
> +            dest = artefacts_dir + "/" + os.path.basename(filename).split("/")[-1]
same in other places below

2023-07-10 09:24 UTC, simonrnss commented on aisdc/attacks/attack_report_formatter.py
> +            self.model_name_from_target = filepath + "\\" + json_report["model_path"]
`"\\"` now?

2023-07-10 09:25 UTC, simonrnss commented on example_notebooks/user_stories/user_story_1/user_story_1_tre.py
> +    t.export_to_file(output_filename=directory + outfile, move_files=True)
does this assume that the separator is in the directory variable? I'd prefer `os.path.join` for stuff like this

2023-07-10 09:27 UTC, simonrnss requested changes
Generally fine, but I'm a little uncomfortable about the use of `+` for forming paths and explicit encoding of path seperators. `os.path.join` and `os.sep` would probably be safer? But, happy to go with what's been done if it matches the format elsewhere in the codebase

2023-07-10 11:03 UTC, yolaj-nhs commented
Thanks @simonrnss for your comments - you're absolutely right. Changes made

2023-07-10 13:11 UTC, yolaj-nhs commented
Converting to draft while I fix code coverage

2023-07-12 11:17 UTC, simonrnss commented on aisdc/attacks/attack_report_formatter.py
> +        release_dir="release_files/",
do we need the trailing /?

2023-07-12 11:17 UTC, simonrnss commented on aisdc/attacks/attack_report_formatter.py
> +        release_dir="release_files/",
ditto below

2023-07-12 11:23 UTC, simonrnss commented on tests/test_attack_report_formatter.py
> +        assert os.path.exists("release_dir/" + output_filename) is True
maybe change to `os.path.exists(os.path.join(...`

2023-07-12 11:23 UTC, simonrnss commented on tests/test_attack_report_formatter.py
> +        g.export_to_file(output_filename, move_files=True, release_dir="release_dir/")
remove `/`

2023-07-12 11:23 UTC, simonrnss commented on tests/test_attack_report_formatter.py
> +        assert os.path.exists("release_dir/" + dummy_model) is True
ditto

2023-07-12 11:24 UTC, simonrnss commented on tests/test_attack_report_formatter.py
> +            release_dir="release_dir/",
ditto

2023-07-12 11:24 UTC, simonrnss commented on tests/test_attack_report_formatter.py
> +        clean_up("release_dir/" + dummy_model)
`os.path.join`

2023-07-12 11:24 UTC, simonrnss approved these changes
Just some more bits where we're explicitly adding dir seps and not using os.path.join

2023-07-12 15:27 UTC, yolaj-nhs commented
@shahzadmumtaz22 I'm merging this into development just so it's out before the end of sprint, I'm happy to make a new issue if you have any comments