added option to not sort
AI-SDC/AI-SDC pull request #90
Opened 2022-12-22 15:41 UTC by simonrnss

Closes #89 

The standard behaviour in MI attacks is to use the _sorted_ predictive probabilities as features. I.e. feature one is the highest probability. This makes the attack easier and less nonlinear (in an ad hoc kind of way of thinking).

This won't always be relevant so I've added an option to not sort them.

Also refactored part of `WorstCaseAttack` to expose this operation for testing.

2022-12-22 15:47 UTC, simonrnss commented
gah...need to fix linting

2023-01-05 16:58 UTC, jim-smith requested changes
Changes to sorting look good but did you mean to include the sparra image?

2023-01-06 09:28 UTC, simonrnss commented
Ah yes, I'll get rid of that

2023-01-06 10:20 UTC, jim-smith approved these changes

2023-01-06 10:21 UTC, merged